AY2425S1-CS2103T-T14-4/tp

docs/AboutUs.md

Closes https://github.com/AY2425S1-CS2103T-T14-4/tp/issues/16

AboutUs Page - Fiona

---

docs/AboutUs.md

AboutUs Page - Pleng

---

docs/AboutUs.md

AboutUs Page - Colin

---

docs/AboutUs.md

AboutUs Page - Le Yew

---

docs/DeveloperGuide.md

Add NFRs to DG

---

docs/DeveloperGuide.md

Closes https://github.com/AY2425S1-CS2103T-T14-4/tp/issues/25

Edit glossary

---

docs/UserGuide.md

Update Quick Start section in User Guide

---

docs/DeveloperGuide.md

Add Preliminary Use Cases to DG

Add Use Cases to DG

---

src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/Person.java
src/test/java/seedu/address/model/person/NameTest.java
src/test/java/seedu/address/model/person/PersonTest.java

Refactor Names for Backend Storage

---

docs/UserGuide.md

Minor edits to User Guide to reflect case-insensitivity of names

Update User Guide to reflect case insensitivity of names

---

src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/PersonCardField.java
src/main/resources/view/PersonListCard.fxml

Updates person card with labels
Previously, the PersonCard representation of fields did not include the corresponding field labels,
this update adds fields labels to the left of the fields
Closes #76

Update Person Card with Labels

---

src/main/java/seedu/address/ui/HelpWindow.java

Update Help's Command Summary to Match Updated User Guide

---

docs/UserGuide.md

Hotfix for GFMD tables for Github Pages deployment of User Guide

Hotfix for GFMD Table Formatting

---

src/test/java/seedu/address/model/person/NameTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/tier/TierTest.java

Updated JUnit Tests for classes Tier, Name and Person

Update tests for Tier, Name and Person

---

src/main/java/seedu/address/logic/parser/AddressBookParser.java

Closes https://github.com/AY2425S1-CS2103T-T14-4/tp/issues/96

Fix issue where incorrect format error is shown when cursor is not at end of command

---

docs/UserGuide.md

Rewrote User Guide to:
- Improve formatting consistency across UG
- Improve formatting using dropdowns/indentations
- Add undocumented commands
- Reduce length of commands details (caused by redundant/repeated information)
Images have yet to be included in the UG. Will do this in the next iteration once UI changes have been complete.
Closes #112.

Rewrite of User Guide

---

src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/Command.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/ExitCommand.java
src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/logic/commands/HelpCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandResultTest.java
src/test/java/seedu/address/logic/commands/ExitCommandTest.java
src/test/java/seedu/address/logic/commands/HelpCommandTest.java

Currently, there is no check after a clear/delete command is given. Now, users are prompted with a message to ask them for confirmation before the command is executed.
Closes https://github.com/AY2425S1-CS2103T-T14-4/tp/issues/106

Implement confirmation check

---

docs/UserGuide.md

Fix Table of Contents in UG

---

docs/diagrams/UiClassDiagram.puml

Update UI class diagram with person detail panel

---

src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/model/person/predicates/StatusStartsWithSubstringPredicate.java
src/test/java/seedu/address/model/person/predicates/StatusStartsWithSubstringPredicateTest.java

Add Filtering by Status

---

src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/client/Income.java
src/main/java/seedu/address/model/client/predicates/IncomeComparisonPredicate.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedClient.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/client/ClientTest.java
src/test/java/seedu/address/model/client/IncomeTest.java
src/test/java/seedu/address/model/client/predicates/IncomeComparisonPredicateTest.java
src/test/java/seedu/address/testutil/ClientBuilder.java
src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
src/test/java/seedu/address/testutil/TypicalClients.java

With the new update, income values can now support values larger than INTEGER_MAX_VALUE and LONG_MAX_VALUE.
This change is reflected throughout usages of Income, namely including the Filter Command
Added tests for Income to reflect these changes.
Closes #155

Update field value in Income Class to be represented in BigInteger

---

README.md
src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/FilterCommand.java

Refactor messages with client/customer/person to Client/Customer

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java

Fix issue with `filter` command

---

src/main/java/seedu/address/ui/StatusPieChart.java

Standardize pie chart legend labels

---

docs/UserGuide.md

Fixed Broken Hyperlinks in User Guide

---

src/main/java/seedu/address/logic/commands/CommandCommons.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/client/predicates/StatusStartsWithSubstringPredicate.java
src/main/java/seedu/address/model/client/predicates/TierStartsWithSubstringPredicate.java
src/main/java/seedu/address/model/status/Status.java
src/main/java/seedu/address/model/tier/Tier.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedStatus.java
src/main/java/seedu/address/storage/JsonAdaptedTier.java
src/main/java/seedu/address/ui/ClientCard.java
src/main/java/seedu/address/ui/ClientDetailPanel.java
src/test/data/JsonSerializableAgentAssistTest/duplicateClientAgentAssist.json
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/ViewCommandTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/model/tier/TierTest.java
src/test/java/seedu/address/testutil/ClientUtil.java

Change tier/status such that users must input t/na or s/na in order to remove the tier/status assigned.

Refactor tier and status

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/test/java/seedu/address/commons/util/StringUtilTest.java

ClientCardFields will now truncate at 3 new line characters, up to an 80 character limit per line

Update truncation logic for ClientCardField

---

docs/DeveloperGuide.md
docs/UserGuide.md

Updated the following:
- Use cases.
- Handling corrupt data.
- Removing unfinished sections.

Update developers' guide

---

docs/DeveloperGuide.md

Update Hyperlinks in DG

---

docs/UserGuide.md

Update Filter Usage Guide and behaviour of Filter by Phone/Email in UG

---

README.md

Update example GUI image in readme

---

src/main/resources/view/ClientDetailPanel.fxml

Fix trancation of name in detail panel

---

src/main/java/seedu/address/model/client/Phone.java

Closes #254.
This error is completely different from the behaviour of phone numbers that we have highlighted in the UG in v1.5.

Fix incorrect error msg for Phone (to resolve Issue #254)

---

docs/DeveloperGuide.md

Update DG for planned feature

---

docs/DeveloperGuide.md

Not sure what was wrong but I edited it until its fixed, tested on my personal repo's github page

Fix large font in DG Glossary

---

src/main/java/seedu/address/ui/HelpWindow.java

Solves #268, and another strictly incorrect example, which would lead to an error message if users tried it.

Fix error in helpwindow
